[2020-04-25 19:05:01,276] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: DAG1.t2 2020-04-25T23:02:04.952229+00:00 [queued]>
[2020-04-25 19:05:01,288] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: DAG1.t2 2020-04-25T23:02:04.952229+00:00 [queued]>
[2020-04-25 19:05:01,289] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-04-25 19:05:01,289] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-04-25 19:05:01,289] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-04-25 19:05:01,397] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): t2> on 2020-04-25T23:02:04.952229+00:00
[2020-04-25 19:05:01,402] {standard_task_runner.py:53} INFO - Started process 14925 to run task
[2020-04-25 19:05:01,613] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: DAG1.t2 2020-04-25T23:02:04.952229+00:00 [running]> karthik-HP-Laptop-15-bs1xx
[2020-04-25 19:05:01,649] {logging_mixin.py:112} INFO - Second function executed
[2020-04-25 19:05:01,650] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-04-25 19:05:01,658] {taskinstance.py:1052} INFO - Marking task as SUCCESS.dag_id=DAG1, task_id=t2, execution_date=20200425T230204, start_date=20200425T230501, end_date=20200425T230501
[2020-04-25 19:05:11,088] {logging_mixin.py:112} INFO - [2020-04-25 19:05:11,088] {local_task_job.py:103} INFO - Task exited with return code 0
